In [17]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np 


math1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

math2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sum = np.add(math1,math2)

print(f"math1 : \n  {math1} \n math2:\n {math2} \n  addition of math1&math2 : \n{sum}")

math1 : 
  [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 math2:
 [[2 3 4]
 [5 6 7]
 [8 9 1]] 
  addition of math1&math2 : 
[[ 3  5  7]
 [ 9 11 13]
 [15 17 10]]


In [19]:
#2. Write a Python Program to Multiply Two Matrices?

import numpy as np 


math1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

math2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sum = np.dot(math1,math2)

print(f"math1 : \n  {math1} \n math2:\n {math2} \n  multiply of math1&math2 : \n{sum}")

math1 : 
  [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 math2:
 [[2 3 4]
 [5 6 7]
 [8 9 1]] 
  multiply of math1&math2 : 
[[ 36  42  21]
 [ 81  96  57]
 [126 150  93]]


In [20]:
#3. Write a Python Program to Transpose a Matrix?
def initializeMatrix(n,v=0):
    M=[]             
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(v)
        M.append(row)
    return(M)

def createMatrix(n):
    
    M=[]             
    print("Enter the element :")
    for i in range(n):
        #stor row
        row =[]
        for j in range(n):
            row.append(int(input()))
        M.append(row)
    return(M)

def printMatrix(M,n):
    for i in range(n):
        for j in range(n):
            print(M[i][j], end=" ")
        print() 
        
def transposeMatrix(M,n,result):
    for i in range(n):
        for j in range(n):
            result[i][j]= M[j][i]
    return result

n=int(input("Enter N for N x N matrix: "))       
M1 = createMatrix(n)
#Display the 2D array
print("Display Array M1 In Matrix Form")
printMatrix(M1,n)

result = initializeMatrix(n)
result = transposeMatrix(M1,n,result)
print("Transposed Matrix")
for r in result:
    print(r)

Enter N for N x N matrix: 4
Enter the element :
1
2
3
4
5
6
7
8
9
1
24
5
4
4
4
4
Display Array M1 In Matrix Form
1 2 3 4 
5 6 7 8 
9 1 24 5 
4 4 4 4 
Transposed Matrix
[1, 5, 9, 4]
[2, 6, 1, 4]
[3, 7, 24, 4]
[4, 8, 5, 4]


In [22]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
str = input("Enter some string")

words = str.split()
words.sort()
for word in words:
    print(word)

Enter some stringhow are you
are
how
you


In [24]:
#5. Write a Python Program to Remove Punctuation From a String?
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

str = input("Enter some string with panctuations")

# remove punctuation from the string
no_punct = ""
for char in str:
    if char not in punctuations:
        no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Enter some string with panctuationshey ! how are you?
hey  how are you
